site_name: Reborn Interactive Regels
theme:
  name: material
  language: nl
  logo: assets/logo.png

  features:
    - toc.follow

  icon:
    annotation: material/arrow-right-circle 

  palette:
    primary: teal
    scheme: slate


nav:
  - Server-Regels: index.md
copyright: Copyright &copy; 2023 Reborn

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg